### PR TITLE
initial commit

### LINKED ISSUE #53: Redesign Platform Toolkit page
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
Redesign the current version of CC’s platform toolkit webpage so that it looks clean and contemporary. Submit it as a pull request to this repository.

Usage of [CC Vocabulary](https://opensource.creativecommons.org/cc-vocabulary/) is recommended but not required.

### PR DESCRIPTION
**Pull request by AndrejaP**
Fixes #53

**Description**
Redesign the current version of CC’s platform toolkit webpage so that it looks clean and contemporary.

**Other information**
In the Figma file with my redesign, I did not include the content from the current version of the CC's platform toolkit page that I would not change much and that would be exactly the same design as the content I included.

### CODE REVIEW

**Comment by kgodey** [comment]
@AndrejaP I cannot see the Figma file. Could you upload it somewhere else and post the link here? (I assumed that the design would be HTML/CSS when I specified the instructions as making a pull request).

**Comment by AndrejaP** [comment]
@kgodey Oh sorry, I never pushed a Figma file to GitHub before. I will code it in HTML, CSS and Javascript and make another pull request when I'm done.

**Comment by kgodey** [comment]
I don't mind just looking at the Figma design if you can send it to me another way.

**Comment by AndrejaP** [comment]
Ah, ok. I committed a pdf file of the design to my forked repository. I am not sure if I should make a pull request again. I am currently coding the 10 FAQ. I don't mind coding this one too, if there is time.

**Comment by kgodey** [comment]
I'd recommend focusing on your final application after one contribution.

**Comment by AndrejaP** [comment]
Thanks a lot for the recommendation. I will try again next time, I feel I need to upgrade my skills to be able to contribute better. I gained some useful knowledge in the process.

**Comment by kgodey** [comment]
@AndrejaP You're welcome! You are welcome to keep contributing as well, the recommendation for the final application was because the deadline is coming up soon. If you're not applying for Outreachy, we hope that you'll still stick around!

**Comment by AndrejaP** [comment]
Thank you. I will!

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this PR.

**Pull request closed without merging**
