### PR TITLE
Fixed the div overflows (in css files: style.css and vocabulary.css) in WHAT COMES AFTER IMPLEMENTATION, ABOUT and…

### LINKED ISSUE #72: Text on buttons overflows
## Description

The text on the buttons overflows on mobile view. I have added screen shots for the same.

## Screenshots

ss2
ss1

## Resolution

- [x] I would be interested in resolving this bug.

### LINKED ISSUE #76: Text Overflow in Divs
## Description
Text overflows in boxes under the "WHAT COMES AFTER IMPLEMENTATION" and "ABOUT" heading when viewed on devices with a width between 768px to around 1300px.

## Reproduction
1. Open this [link](https://creativecommons.org/platform/toolkit/).
2. Open the Developer Tools
3. Change the screen width accordingly
4. See the overflow.

## Expectation
There should not be any overflow in these cases too.

## Screenshots
Screenshot from 2021-01-22 22-52-39
Screenshot from 2021-01-22 22-52-52

## Environment
 - Device: laptop
 - OS: Ubuntu 20.04
 - Browser: Chrome, Firefox
 - Version: 88.0.4324

## Resolution
- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by Ayush-023**
… WHO IS THIS PAGE FOR headings when viewed on devices with a width between 768px to around 1300px.

## Fixes

Fixes #76  by @shubhanshu02

## Description

This PR fixes the overflows in the divs under headings: What comes after implementation?, About, Who is this page for? when viewed on devices with a width between 768px to around 1300px.

## Technical details

Changed the hardcoded sizes in the CSS to fluid sizes. 

## Screenshots

Screenshot (40)
Screenshot (38)
Screenshot (39)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by shubhanshu02 — COMMENTED** [review]
I think you mentioned the wrong issue; it's #76. The overflow in the divs seems to be gone by these changes, just that the text size in buttons has got a bit smaller to read.

**Comment by Ayush-023** [comment]
> I think you mentioned the wrong issue; it's #76. The overflow in the divs seems to be gone by these changes, just that the text size in buttons has got a bit smaller to read.

Yeah, sorry I mentioned the wrong issue. There is overflow in other buttons on the page too, just the background color and text color is white so it isn't that much visible.
All the other overflow problems seem fixed?

**Comment by shubhanshu02** [comment]
> Yeah, sorry I mentioned the wrong issue. There is overflow in other buttons on the page too, just the background color and text color is white so it isn't that much visible.
> All the other overflow problems seem fixed?
> What should I do?

@Ayush-023, as far as I can explore with the HTML, I cannot see any overflow now. Wait for any member to review this PR.

**Review by zackkrida — APPROVED** [review]
I'm content with this solution. Thank you! Anyone involved here who wants to fix the button issue in #72 is welcome to 🎊

**Pull request merged**
